### ISSUE TITLE
how to trigger interrupts?

### ISSUE THREAD

**Issue by nippur72** [dimiro1/Z80-js#2]
I have not found a way to trigger interrupts in the CPU... is that a missing feature?

Ideally there should be a function:

```ts
cpu.interrupt(nmi: boolean, data: number);
```

**Comment by dimiro1** [comment]
Hello, @nippur72 It is missing this feature an many other :(. Unfortunately, I don't have much time to implement the missing features. I really appreciate your interest in this library and would be very nice to have a PR from you.
